using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Arac_Takip_v1._00
{
    public partial class Yakit_Giris : Form
    {
        MsSQL veriTabani = new MsSQL();
        public Yakit_Giris()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
        }

        private void YakitGiris_Load(object sender, EventArgs e)
        {
            // TODO: Bu kod satırı 'aracTakipDBDataSet1.Arac_Bilgileri' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
            this.arac_BilgileriTableAdapter.Fill(this.aracTakipDBDataSet1.Arac_Bilgileri);
            // TODO: Bu kod satırı 'aracTakipDBDataSet1.v_SurucuBilgileri' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
            this.v_SurucuBilgileriTableAdapter.Fill(this.aracTakipDBDataSet1.v_SurucuBilgileri);
            // TODO: Bu kod satırı 'aracTakipDBDataSet1.v_YakitBilgileri' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
            this.v_YakitBilgileriTableAdapter.Fill(this.aracTakipDBDataSet1.v_YakitBilgileri);
            ViewGüncelle();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {

            veriTabani.YakitGirisi(belgeNo_Yakit.Text, plakaNo_yakit.Text, yakit_Alinan.Text.Replace(',', '.'), total_Yakit.Text.Replace(',', '.'), "" + surucuAdi_yakit.SelectedValue, Yakit_tarih.Text);
            ViewGüncelle();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            veriTabani.VeriSil(Yakit_Bilgileri.Name, "Belge_No", yakitGiris.GetRowCellValue(yakitGiris.FocusedRowHandle, "Belge_No").ToString());
            ViewGüncelle();
        }
        private void ViewGüncelle()
        {
            // TODO: Bu kod satırı 'aracTakipDBDataSet1.v_YakitBilgileri' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
            this.v_YakitBilgileriTableAdapter.Fill(this.aracTakipDBDataSet1.v_YakitBilgileri);
            // TODO: Bu kod satırı 'aracTakipDBDataSet1.v_SurucuBilgileri' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
            this.v_SurucuBilgileriTableAdapter.Fill(this.aracTakipDBDataSet1.v_SurucuBilgileri);
            // TODO: Bu kod satırı 'aracTakipDBDataSet1.Arac_Bilgileri' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
            this.arac_BilgileriTableAdapter.Fill(this.aracTakipDBDataSet1.Arac_Bilgileri);
            belgeNo_Yakit.Text = "";
            yakit_Alinan.Text = "";
            total_Yakit.Text = "";
        }
    }
}
